### ISSUE TITLE
还会有更新吗

### ISSUE THREAD

**Issue by Qquanwei** [kagxin/epollTcpServer#1]
epollTcpServer使用了epoll了为啥还要用thread呢
 希望author出个2.0

**Comment by kagxin** [comment]
确实是的，如果用了epoll又用了多线程，那就没有，用epoll异步的必要了。有空再回头看一下，多谢指出。


来自 魅族 PRO 6s

-------- 原始邮件 --------
发件人：Qquanwei <notifications@github.com>
时间：周二 3月14日 15:00
收件人：kagxin/epollTcpServer <epollTcpServer@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[kagxin/epollTcpServer] 还会有更新吗 (#1)
